# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_underlying_cpp <- function(S, D, T, r, vol, tol) {
    .Call('_DtD_get_underlying_cpp', PACKAGE = 'DtD', S, D, T, r, vol, tol)
}

#' @export
BS_call <- function(V, D, T, r, std) {
    .Call('_DtD_BS_call', PACKAGE = 'DtD', V, D, T, r, std)
}

BS_fit_cpp <- function(S, D, T, r, time, vol_start, method, tol, eps) {
    .Call('_DtD_BS_fit_cpp', PACKAGE = 'DtD', S, D, T, r, time, vol_start, method, tol, eps)
}

