# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_underlying_cpp <- function(S, D, T, r, std, tol = 1e-12) {
    .Call('_DtD_get_underlying_cpp', PACKAGE = 'DtD', S, D, T, r, std, tol)
}

kmv <- function(S, D, T, r, time, vol, tol = 1e-12) {
    .Call('_DtD_kmv', PACKAGE = 'DtD', S, D, T, r, time, vol, tol)
}

#' @export
BS_call <- function(V, D, T, r, std) {
    .Call('_DtD_BS_call', PACKAGE = 'DtD', V, D, T, r, std)
}

